int main() {
        int x; cin >> x;
        int left;
        int k = x / 100;
        cout << k<<"*100" << " ";
        left = x - (k*100);
        k = left / 50;
        cout << k*50 << " ";
        left = left - (k*50);
        k = left / 20;
        cout << k<<"*20" << " ";
        left = left - (k*20);
        k = left / 10;
        cout << k * 10 << " ";
        left = left - (k*10);
        k = left / 5;
        cout << k * 5 << " ";
        left =  left- (k*5);
        k = left / 2;
        cout << k <<"*2" << " ";
        left = left - (k*2);
        cout << (left==1) << " ";
        return 0;
